v: 2.6.0
overrideConfig: false
ie:
  - DS_Store
  - less
  - scss
  - js
id:
  - scss
  - .svn
  - .sass-cache
  - fonts
  - icons
cleanPublic: 'true'
patternStates:
  - inprogress
  - inreview
  - complete
styleGuideExcludes: ''
cacheBusterOn: 'true'
exportDir: export
publicDir: ../../../dist/app-pl/pl/
sourceDir: ../../../source/urban/
defaultPattern: protons-welcome
defaultShowPatternInfo: false
ishMinimum: '240'
ishMaximum: '2600'
ishControlsHide:
  - hay
lineageMatch: '{%([ ]+)?include( |\()[&quot;\&#039;]([A-Za-z0-9-_]+)[&quot;\&#039;](\))?(.*)%}'
lineageMatchKey: 3
patternExtension: twig
twigDebug: true
twigAutoescape: false
twigDefaultDateFormat: ''
twigDefaultIntervalFormat: ''
twigMacroExt: macro.twig
twigFilterExt: filter.php
twigFunctionExt: function.php
twigTagExt: tag.php
twigTestExt: test.php
styleguideKit: pattern-lab/styleguidekit-twig-default
styleguideKitPath: vendor/pattern-lab/styleguidekit-twig-default
plugins:
  faker:
    enabled: true
    locale: en_US
  twigNamespaces:
    enabled: true
    namespaces:
      protons:
        paths:
          - ../../../source/urban/_patterns/00-protons
          - ../../../source/urban/_patterns/00-protons/utilities
      atoms:
        paths:
          - ../../../source/urban/_patterns/01-atoms
          - ../../../source/urban/_patterns/01-atoms/alert
          - ../../../source/urban/_patterns/01-atoms/badge
          - ../../../source/urban/_patterns/01-atoms/branding
          - ../../../source/urban/_patterns/01-atoms/breadcrumb
          - ../../../source/urban/_patterns/01-atoms/button
          - ../../../source/urban/_patterns/01-atoms/dropdown
          - ../../../source/urban/_patterns/01-atoms/grid
          - ../../../source/urban/_patterns/01-atoms/image
          - ../../../source/urban/_patterns/01-atoms/list-group
          - ../../../source/urban/_patterns/01-atoms/svgicon
      molecules:
        paths:
          - ../../../source/urban/_patterns/02-molecules
          - ../../../source/urban/_patterns/02-molecules/card
          - ../../../source/urban/_patterns/02-molecules/carousel
          - ../../../source/urban/_patterns/02-molecules/jumbotron
          - ../../../source/urban/_patterns/02-molecules/nav
          - ../../../source/urban/_patterns/02-molecules/pagination
          - ../../../source/urban/_patterns/02-molecules/vue-widget
      organisms:
        paths:
          - ../../../source/urban/_patterns/03-organisms
          - ../../../source/urban/_patterns/03-organisms/accordion
          - ../../../source/urban/_patterns/03-organisms/article
          - ../../../source/urban/_patterns/03-organisms/card-grid
          - ../../../source/urban/_patterns/03-organisms/footer
          - ../../../source/urban/_patterns/03-organisms/navbar
      templates:
        paths:
          - ../../../source/urban/_patterns/04-templates
          - ../../../source/urban/_patterns/04-templates/basic-page
      pages:
        paths:
          - ../../../source/urban/_patterns/05-pages
