name: your-site-name
recipe: pantheon
config:
  framework: drupal8
  site: your-site-name
  id: insert-here-after-build-tools

services:
  appserver:
#    xdebug: true
    config:
      drush: global:8.1.17
    overrides:
      services:
        image: urbaninstitute/lando-build:v8
#    run:
#      - "cd $LANDO_MOUNT && composer update"

tooling:
  npm:
    service: appserver
  node:
    service: appserver
  gulp:
    service: appserver
  tika:
    service: appserver
    cmd: java -jar /srv/bin/tika-app-1.1.jar
  quickstart:
    service: appserver
    cmd: bash bin/lando-quickstart.sh
    description: Runs composer install and compiles Particle theme.
  particle:
    service: appserver
    cmd: bash bin/particle.sh
    description: Compiles Particle theme in Lando (for quickstart or non frontend work).
  clean:
    service: appserver
    cmd: bash bin/clean.sh
    description: Removes all artifacts installed by Composer or NPM (includes Particle artifacts).
  drupal:
    cmd:
      - "/app/vendor/bin/drupal"

# Enable events after install.

#events:
#  post-pull:
#    - appserver: cd $LANDO_WEBROOT && drush updatedb -y
#    - appserver: cd $LANDO_WEBROOT && drush entup -y
#    - appserver: cd $LANDO_WEBROOT && drush cim -y
#    - appserver: cd $LANDO_WEBROOT && drush cr
